### ISSUE TITLE
Add option to unsubscribe user when membership expires

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/RCP-MailChimp#14]
We've had a couple requests for this. Logging an issue in case we get more requests or decide to do it.

**Comment by nosegraze** [comment]
I've gotten several requests for this too.

**Comment by pippinsplugins** [comment]
This can be done in the MailChimp Pro plugin from @ghost1227. Unless we merge the plugins together, I don't think we should do this.

**Comment by nosegraze** [comment]
Makes sense. I'm fine with not doing it.

Presumably this can be done with Zapier anyway when we get that add-on.

**Comment by mindctrl** [comment]
It looks like this feature is not in the Pro version.

**Comment by pippinsplugins** [comment]
It is, kind of. The pro version stores merge tags for member statuses. MailChimp lets you set up automation that automatically adds / removes members from lists and groups based on their merge tag values, so site owners just need to set up a "Unsubscribe Routine" that removes members when their subscription ID merge tag is X and their subscription status is Y.
