### ISSUE TITLE
Re-send MailChimp confirmation email for 'pending' users already on the list

### ISSUE THREAD

**Issue by ashleyfae** [restrictcontentpro/RCP-MailChimp#32]
Example:

- User is already on MailChimp list as `pending`. This is due to signing up previously somehow but never confirming email.
- User registers through RCP and opts in to MailChimp list.
- User will not be added to the list due to API error: `x is already a list member. Use PUT to insert or update list members.`

It would be nice if we could check for existing members and re-send confirmation emails if they're already on the list as `pending`. I think we can do this by simply updating the existing member and setting their status to `pending` again.

**Comment by nosegraze** [comment]
PR: #37

This went a bit further than I expected. XD I added the class because I didn't want to have to redo all the API key / data center stuff when putting together another request.

Anyway haven't tested this yet, just pushing it up. Will probably test tomorrow.

**Comment by nosegraze** [comment]
Re-reviewed this and I'm still very happy with it.

@mihaijoldis Can you please run through the above test list again and make sure everything still works?

**Comment by mihaijoldis** [comment]
@ashleyfae all good.
Took me a while to find this as for some reason i did not have a notification for the mention
