### ISSUE TITLE
Update to MailChimp API 3.0

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/RCP-MailChimp#5]
We need to update to v3 API, since v2 expires at end of the year.

**Comment by mindctrl** [comment]
Related to this, there's a PHP deprecated notice in the included MCAPI library.

```

**Comment by nosegraze** [comment]
PR: #16

Sorry I kind of didn't notice this was assigned to you @mindctrl until I made the PR. Hope that's okay.

**Comment by mindctrl** [comment]
Ha! I don't even remember assigning it to myself. Yay for the PR!

**Comment by pippinsplugins** [comment]
That is soooo much simpler than I expected it to be.
