### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/RCP-MailChimp#7]
- [x] Add PHPDocs
- [x] Escape all settings values and text for "Save Options" button
- [x] In `rcp_get_mailchimp_lists()` check if `$list_data` is an array before starting the `foreach` loop
- [x] Make "MailChimp" string available for translation in `rcp_add_mc_signup_notice()`
- [x] Invalid stylesheet URL being added in `rcp_mailchimp_admin_styles()` due to using `RCP_PLUGIN_DIR` instead of `RCP_PLUGIN_URL`

**Comment by nosegraze** [comment]
PR: #8

I just removed the CSS all together since no styling was actually being used anyway (I checked - no visual differences). But I can just keep it in and fix it if preferred.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by mindctrl** [comment]
For some reason I wasn't watching this repo, so I missed all this. @nosegraze there's a merge conflict now. If you want to fix that up I'll give this a whirl sometime over the next week.

**Comment by nosegraze** [comment]
Updated!
